### ISSUE TITLE
Not found the file guitar_separator_CNN-2000.meta 

### ISSUE THREAD

**Issue by shiju-john** [saumye1/cocktail-party-deep-learning#3]
I just tried the given project . Could you please share the guitar_separator_CNN-2000.meta also

**Comment by logiclessindian** [comment]
same here. getting following error
`
january@rajberryVM:~/rajberry/cocktail-party-deep-learning/Cocktail_party_CNN$ python guitar_separate_test_CNN.py guitar_nish.wav speech.wav 
toh...ho gaya yaha tak
2018-01-14 20:38:47.282242: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX
Traceback (most recent call last):
  File "guitar_separate_test_CNN.py", line 78, in <module>
    saver = tf.train.import_meta_graph('guitar_separator_CNN-2000.meta')
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 1803, in import_meta_graph
    meta_graph_def = meta_graph.read_meta_graph_file(meta_graph_or_file)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/meta_graph.py", line 555, in read_meta_graph_file
    raise IOError("File %s does not exist." % filename)
IOError: File guitar_separator_CNN-2000.meta does not exist.
january@rajberryVM:~/rajberry/cocktail-party-deep-learning/Cocktail_party_CNN$
`
how to fix it ??

**Comment by saumye1** [comment]
@shiju-john  I have added the .meta file. @logiclessindian  It won't still run for a different error now. As the trained network data file is still missing which is 1.3 GBs(github doesn't allow such large uploads). If you don't want to train your own network using the other files, I can provide you mine on your email?

**Comment by tfgod** [comment]
I believe you need the checkpoint and data-00000 file. Can you add these files and see if it works? Also can you email me (asd37050 at gmail dot com) as I need to generate a pb file and don't have the resources to train.
